baseURL = "http://example.com"
title = "Get Advice | Shine"

contentdir = "hugo/content"
dataDir = "hugo/data"
layoutdir = "hugo/layouts"
themesdir = "hugo/themes"
archetypedir = "hugo/archetype"
destination = "public"
publishdir = "public"
staticdir = "hugo/static"
theme =  ""

googleAnalytics = ""
paginate = 9

[params]
  description = "Shine theme for Hugo"
  # dateFormat = "2006, Jan 2"
  copyrightStartYear = "2015"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Chris"

[author.social]
  facebook = ""
  github = ""
  twitter = ""

[permalinks]
  post = "articles/:slug/"
  page = "/:slug/"
  author = "/:slug/"

defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
