title = "Get Advice"
contentdir = "hugo/content"
dataDir = "hugo/data"
layoutdir = "hugo/layouts"
themesdir = "hugo/themes"
archetypedir = "hugo/archetype"
destination = "public"
publishdir = "public"
staticdir = "hugo/static"
theme =  ""
googleAnalytics = "UA-68971267-1"
paginate = 9
enableRobotsTXT = true
languageCode = "en"

[params]
  description = "Career and life advice from real people. Get daily fulfillment and read up on how to live your best life."
  google_tag_manager="GTM-PZHRDB"
  google_optimize="GTM-MTMSV5Q"
  fb_pixel=190488081450568
  # dateFormat = "2006, Jan 2"
  copyrightStartYear = "2015"
  infinite_scroll = true
  shine_logo = "https://images.ctfassets.net/awpxl2koull4/6Ge2cCqfKg0IM8CIsOMiq6/bc0dee5dd91c1b37a155c220e95893d4/shine-logo-nav-122018.png"
  share_description = "Career and life advice from real people. Get daily fulfillment and read up on how to live your best life."

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Shine"

[author.social]
  facebook = ""
  github = ""
  twitter = ""

[permalinks]
  post = "articles/:slug/"
  page = "/:slug/"
  author = "/:slug/"

defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
