baseURL = "http://example.com"
title = "Get Advice | Shine"

contentdir = "hugo/content"
dataDir = "hugo/data"
layoutdir = "hugo/layouts"
themesdir = "hugo/themes"
archetypedir = "hugo/archetype"
destination = "public"
publishdir = "public"
staticdir = "hugo/static"
theme =  ""
googleAnalytics = "UA-68971267-1"
paginate = 9

[params]
  description = "Career and life advice from real people. Get daily fulfillment and read up on how to live your best life."
  google_tag_manager="GTM-XXXX"
  # dateFormat = "2006, Jan 2"
  copyrightStartYear = "2015"
  infinite_scroll = true
  shine_logo = "https://images.contentful.com/awpxl2koull4/FFhnW3pbga4qmCOM24kmc/8c718dac9a5357db86c55b637461f4f3/Shine-logo-web.png"
  share_description = "Career and life advice from real people. Get daily fulfillment and read up on how to live your best life."

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Shine"

[author.social]
  facebook = ""
  github = ""
  twitter = ""

[permalinks]
  post = "articles/:slug/"
  page = "/:slug/"
  author = "/:slug/"

defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
